### ISSUE TITLE
"fread" in the 0.haplomagic.R

### ISSUE THREAD

**Issue by yan-cheng-lin** [GoliczGenomeLab/haploMAGIC#1]
Hello,

Thank you for your program.
I was interested in your program, however, I always failed to run with your example, so I look into your R script. 
It failed in your first commend of 0.haplomagic.R, "suppressMessages(suppressWarnings(if(!require("fread")){ install.packages("fread") }))"

I guess "fread" is not a package (mabye is the function of R/data.table), so I delete this line, and I can run it successfully.
Just want to know if it is the really issue of it?
Thank you. 

Best regards,
Yan-Cheng

**Comment by jamonterotena** [comment]
Thank you for your question @yan-cheng-lin. That code line is an error, as you indicated, so I will proceed to delete it.

haploMAGIC is built to run only with the R base package, so instead of `fread()`, tables are imported with `read.table()`.
